# Generated by Django 5.1.1 on 2024-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_employee_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
