# Generated by Django 5.0.6 on 2024-05-19 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='surname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='name',
        ),
    ]
