# Generated by Django 5.0.6 on 2024-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pizza', '0002_rename_surname_courier_name_rename_title_pizza_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizza/'),
        ),
    ]
