# Generated by Django 5.0.6 on 2024-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pizza', '0005_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
