# Generated by Django 5.0.6 on 2024-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pizza', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
