# Generated by Django 5.0.6 on 2024-05-23 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pizza', '0007_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
    ]
