# Generated by Django 5.0.6 on 2024-05-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_order_discount'),
        ('registration', '0004_alter_customer_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to='registration.courier'),
        ),
    ]
