# Generated by Django 5.0.6 on 2024-05-23 15:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
