
    version: "3.9"
    
    services:
      node:
        build: .
        container_name: express_app
        ports:
          - 3000:3000
        restart: always
        volumes:
          - ./:/usr/src/app
        networks:
          - mongo-network
        depends_on:
          - mongodb
    
      mongodb:
        image: mongo
        container_name: mongo
        restart: always
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
          - mongo_db:/data/db
          - config_db:/data/configdb
        networks:
          - mongo-network
    
      mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: password
          ME_CONFIG_MONGODB_SERVER: mongodb
        networks:
          - mongo-network
        depends_on:
          - mongodb
    
    networks:
      mongo-network:
    
    volumes:
      mongo_db:
      config_db:
